/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-108112-g3ce6fa6b6d-20220912"
#endif /* AVUTIL_FFVERSION_H */
